"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: spatial.anchors
  IDL file: anchors.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from spatialdds18 import spatial

if TYPE_CHECKING:
    import builtin
    import spatial.core


MODULE_ID = "spatial.anchors/1.8"
Time = types.typedef['spatialdds18.spatial.anchors.Time', 'spatialdds18.builtin.Time']
GeoPose = types.typedef['spatialdds18.spatial.anchors.GeoPose', 'spatialdds18.spatial.core.GeoPose']
FrameRef = types.typedef['spatialdds18.spatial.anchors.FrameRef', 'spatialdds18.spatial.core.FrameRef']

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class AnchorEntry(idl.IdlStruct, typename="spatial.anchors.AnchorEntry"):
    anchor_id: str
    annotate.key("anchor_id")
    name: str
    geopose: 'spatialdds18.spatial.anchors.GeoPose'
    confidence: types.float64
    tags: types.sequence[str, 8]
    stamp: 'spatialdds18.spatial.anchors.Time'
    checksum: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class AnchorSet(idl.IdlStruct, typename="spatial.anchors.AnchorSet"):
    set_id: str
    annotate.key("set_id")
    title: str
    provider_id: str
    map_frame: 'spatialdds18.spatial.anchors.FrameRef'
    version: str
    tags: types.sequence[str, 16]
    center_lat: types.float64
    center_lon: types.float64
    radius_m: types.float64
    anchors: types.sequence['spatialdds18.spatial.anchors.AnchorEntry', 256]
    stamp: 'spatialdds18.spatial.anchors.Time'
    checksum: str

@annotate.final
class AnchorOp(idl.IdlEnum, typename="spatial.anchors.AnchorOp", default="ADD"):
    ADD = 0
    UPDATE = 1
    REMOVE = 2

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class AnchorDelta(idl.IdlStruct, typename="spatial.anchors.AnchorDelta"):
    set_id: str
    annotate.key("set_id")
    op: 'spatialdds18.spatial.anchors.AnchorOp'
    entry: 'spatialdds18.spatial.anchors.AnchorEntry'
    revision: types.uint64
    stamp: 'spatialdds18.spatial.anchors.Time'
    post_checksum: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class AnchorSetRequest(idl.IdlStruct, typename="spatial.anchors.AnchorSetRequest"):
    set_id: str
    annotate.key("set_id")
    up_to_revision: types.uint64


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class AnchorSetResponse(idl.IdlStruct, typename="spatial.anchors.AnchorSetResponse"):
    set_id: str
    annotate.key("set_id")
    revision: types.uint64
    set: 'spatialdds18.spatial.anchors.AnchorSet'


