"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: spatial.core
  IDL file: core.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# generate_types_18.py: idlc emits this discriminator as a bare name
from spatialdds18.spatial.common._types import CovarianceType

# root module import for resolving types
from spatialdds18 import spatial

if TYPE_CHECKING:
    import builtin
    import spatial.common


MODULE_ID = "spatial.core/1.8"
Time = types.typedef['spatialdds18.spatial.core.Time', 'spatialdds18.builtin.Time']

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class PoseSE3(idl.IdlStruct, typename="spatial.core.PoseSE3"):
    t: 'spatialdds18.spatial.common.Vec3'
    q: 'spatialdds18.spatial.common.QuaternionXYZW'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Aabb3(idl.IdlStruct, typename="spatial.core.Aabb3"):
    min_xyz: 'spatialdds18.spatial.common.Vec3'
    max_xyz: 'spatialdds18.spatial.common.Vec3'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class TileKey(idl.IdlStruct, typename="spatial.core.TileKey"):
    x: types.uint32
    annotate.key("x")
    y: types.uint32
    annotate.key("y")
    z: types.uint32
    annotate.key("z")
    level: types.uint8
    annotate.key("level")

@annotate.final
class PatchOp(idl.IdlEnum, typename="spatial.core.PatchOp", default="ADD"):
    ADD = 0
    REPLACE = 1
    REMOVE = 2

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class BlobRef(idl.IdlStruct, typename="spatial.core.BlobRef"):
    blob_id: str
    role: str
    checksum: str

FrameRef = types.typedef['spatialdds18.spatial.core.FrameRef', 'spatialdds18.spatial.common.FrameRef']

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class TileMeta(idl.IdlStruct, typename="spatial.core.TileMeta"):
    key: 'spatialdds18.spatial.core.TileKey'
    annotate.key("key")
    has_tile_id_compat: bool
    tile_id_compat: str
    aabb: 'spatialdds18.spatial.core.Aabb3'
    version: types.uint64
    encoding: str
    checksum: str
    blob_ids: types.sequence[str, 32]
    has_centroid_llh: bool
    centroid_llh: 'spatialdds18.spatial.common.Vec3'
    has_radius_m: bool
    radius_m: types.float64
    schema_version: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class TilePatch(idl.IdlStruct, typename="spatial.core.TilePatch"):
    key: 'spatialdds18.spatial.core.TileKey'
    annotate.key("key")
    revision: types.uint64
    op: 'spatialdds18.spatial.core.PatchOp'
    target: str
    blobs: types.sequence['spatialdds18.spatial.core.BlobRef', 8]
    post_checksum: str
    stamp: 'spatialdds18.spatial.core.Time'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class BlobChunk(idl.IdlStruct, typename="spatial.core.BlobChunk"):
    blob_id: str
    annotate.key("blob_id")
    index: types.uint32
    annotate.key("index")
    total_chunks: types.uint32
    crc32: types.uint32
    data: types.sequence[types.uint8, 65535]

@annotate.final
class EdgeTypeCore(idl.IdlEnum, typename="spatial.core.EdgeTypeCore", default="ODOM"):
    ODOM = 0
    LOOP = 1


@annotate.appendable
class CovMatrix(idl.IdlUnion, discriminator=CovarianceType, discriminator_is_key=False, typename="spatial.core.CovMatrix"):
    none: types.case[[CovarianceType.COV_NONE], types.uint8]
    pos: types.case[[CovarianceType.COV_POS3], 'spatialdds18.spatial.common.Mat3x3']
    pose: types.case[[CovarianceType.COV_POSE6], 'spatialdds18.spatial.common.Mat6x6']
    rot: types.case[[CovarianceType.COV_ROT3], 'spatialdds18.spatial.common.Mat3x3']
    pose_twist: types.case[[CovarianceType.COV_POSE6_TWIST6], 'spatialdds18.spatial.common.Mat12x12']


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class FramedPose(idl.IdlStruct, typename="spatial.core.FramedPose"):
    pose: 'spatialdds18.spatial.core.PoseSE3'
    frame_ref: 'spatialdds18.spatial.core.FrameRef'
    cov: 'spatialdds18.spatial.core.CovMatrix'
    stamp: 'spatialdds18.spatial.core.Time'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class PlannedWaypoint(idl.IdlStruct, typename="spatial.core.PlannedWaypoint"):
    pose: 'spatialdds18.spatial.core.PoseSE3'
    stamp: 'spatialdds18.spatial.core.Time'
    has_velocity: bool
    velocity: 'spatialdds18.spatial.common.Vec3'
    has_uncertainty: bool
    position_uncertainty_m: types.float32
    has_confidence: bool
    confidence: types.float32


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class PlannedTrajectory(idl.IdlStruct, typename="spatial.core.PlannedTrajectory"):
    agent_id: str
    annotate.key("agent_id")
    plan_id: str
    plan_revision: types.uint32
    frame_ref: 'spatialdds18.spatial.core.FrameRef'
    waypoints: types.sequence['spatialdds18.spatial.core.PlannedWaypoint', 256]
    has_goal_pose: bool
    goal_pose: 'spatialdds18.spatial.core.PoseSE3'
    has_horizon_sec: bool
    horizon_sec: types.float32
    has_replan_rate_hz: bool
    replan_rate_hz: types.float32
    stamp: 'spatialdds18.spatial.core.Time'
    schema_version: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class ComponentRef(idl.IdlStruct, typename="spatial.core.ComponentRef"):
    topic: str
    key: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class EntityBinding(idl.IdlStruct, typename="spatial.core.EntityBinding"):
    entity_id: str
    annotate.key("entity_id")
    entity_class: str
    components: types.sequence['spatialdds18.spatial.core.ComponentRef', 16]
    has_pose: bool
    pose: 'spatialdds18.spatial.core.FramedPose'
    stamp: 'spatialdds18.spatial.core.Time'
    source_id: str
    schema_version: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Node(idl.IdlStruct, typename="spatial.core.Node"):
    map_id: str
    annotate.key("map_id")
    node_id: str
    annotate.key("node_id")
    pose: 'spatialdds18.spatial.core.PoseSE3'
    cov: 'spatialdds18.spatial.core.CovMatrix'
    stamp: 'spatialdds18.spatial.core.Time'
    frame_ref: 'spatialdds18.spatial.core.FrameRef'
    source_id: str
    seq: types.uint64
    graph_epoch: types.uint64


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Edge(idl.IdlStruct, typename="spatial.core.Edge"):
    map_id: str
    annotate.key("map_id")
    edge_id: str
    annotate.key("edge_id")
    from_id: str
    to_id: str
    type: 'spatialdds18.spatial.core.EdgeTypeCore'
    T_from_to: 'spatialdds18.spatial.core.PoseSE3'
    information: 'spatialdds18.spatial.common.Mat6x6'
    stamp: 'spatialdds18.spatial.core.Time'
    source_id: str
    seq: types.uint64
    graph_epoch: types.uint64


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class GeoPose(idl.IdlStruct, typename="spatial.core.GeoPose"):
    lat_deg: types.float64
    lon_deg: types.float64
    alt_m: types.float64
    q: 'spatialdds18.spatial.common.QuaternionXYZW'
    stamp: 'spatialdds18.spatial.core.Time'
    cov: 'spatialdds18.spatial.core.CovMatrix'

@annotate.final
class GnssFixType(idl.IdlEnum, typename="spatial.core.GnssFixType", default="NO_FIX"):
    NO_FIX = 0
    FIX_2D = 1
    FIX_3D = 2
    DGPS = 3
    RTK_FLOAT = 4
    RTK_FIXED = 5
    SBAS = 6
    DEAD_RECKONING = 7
    UNKNOWN_FIX = 8

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class NavSatStatus(idl.IdlStruct, typename="spatial.core.NavSatStatus"):
    gnss_id: str
    annotate.key("gnss_id")
    fix_type: 'spatialdds18.spatial.core.GnssFixType'
    service: types.uint16
    num_satellites: types.uint16
    has_dop: bool
    pdop: types.float32
    hdop: types.float32
    vdop: types.float32
    has_velocity: bool
    speed_mps: types.float32
    course_deg: types.float32
    has_diff_age: bool
    diff_age_s: types.float32
    diff_station_id: types.uint16
    stamp: 'spatialdds18.spatial.core.Time'
    schema_version: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class GeoAnchor(idl.IdlStruct, typename="spatial.core.GeoAnchor"):
    anchor_id: str
    annotate.key("anchor_id")
    map_id: str
    frame_ref: 'spatialdds18.spatial.core.FrameRef'
    geopose: 'spatialdds18.spatial.core.GeoPose'
    method: str
    confidence: types.float64
    checksum: str
    cov: 'spatialdds18.spatial.core.CovMatrix'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class FrameTransform(idl.IdlStruct, typename="spatial.core.FrameTransform"):
    transform_id: str
    annotate.key("transform_id")
    parent_ref: 'spatialdds18.spatial.core.FrameRef'
    child_ref: 'spatialdds18.spatial.core.FrameRef'
    T_parent_child: 'spatialdds18.spatial.core.PoseSE3'
    stamp: 'spatialdds18.spatial.core.Time'
    cov: 'spatialdds18.spatial.core.CovMatrix'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class SnapshotRequest(idl.IdlStruct, typename="spatial.core.SnapshotRequest"):
    key: 'spatialdds18.spatial.core.TileKey'
    annotate.key("key")
    up_to_revision: types.uint64


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class SnapshotResponse(idl.IdlStruct, typename="spatial.core.SnapshotResponse"):
    key: 'spatialdds18.spatial.core.TileKey'
    annotate.key("key")
    revision: types.uint64
    blob_ids: types.sequence[str, 64]
    checksum: str


