"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: spatial.owm
  IDL file: owm.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from spatialdds18 import spatial

if TYPE_CHECKING:
    import builtin
    import spatial.common
    import spatial.core


MODULE_ID = "spatial.owm/0.1"
Time = types.typedef['spatialdds18.spatial.owm.Time', 'spatialdds18.builtin.Time']
PoseSE3 = types.typedef['spatialdds18.spatial.owm.PoseSE3', 'spatialdds18.spatial.core.PoseSE3']
Aabb3 = types.typedef['spatialdds18.spatial.owm.Aabb3', 'spatialdds18.spatial.core.Aabb3']
FrameRef = types.typedef['spatialdds18.spatial.owm.FrameRef', 'spatialdds18.spatial.common.FrameRef']
KV = types.typedef['spatialdds18.spatial.owm.KV', 'spatialdds18.spatial.common.KV']
@annotate.final
class ModelLayer(idl.IdlEnum, typename="spatial.owm.ModelLayer", default="STATIC"):
    STATIC = 0
    SLOW = 1
    FAST = 2
@annotate.final
class Basis(idl.IdlEnum, typename="spatial.owm.Basis", default="OBSERVED"):
    OBSERVED = 0
    DECLARED = 1
    AUTHORED = 2
    DERIVED = 3
@annotate.final
class LifecycleState(idl.IdlEnum, typename="spatial.owm.LifecycleState", default="ACTIVE"):
    ACTIVE = 0
    UNOBSERVED = 1
    RETIRED = 2
    SUPERSEDED = 3

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Entity(idl.IdlStruct, typename="spatial.owm.Entity"):
    entity_id: str
    annotate.key("entity_id")
    basis: 'spatialdds18.spatial.owm.Basis'
    type_uris: types.sequence[str, 4]
    layer: 'spatialdds18.spatial.owm.ModelLayer'
    frame_ref: 'spatialdds18.spatial.owm.FrameRef'
    has_pose: bool
    pose: 'spatialdds18.spatial.owm.PoseSE3'
    has_extent: bool
    extent: 'spatialdds18.spatial.owm.Aabb3'
    properties: types.sequence['spatialdds18.spatial.owm.KV', 32]
    external_refs: types.sequence['spatialdds18.spatial.owm.KV', 8]
    content_refs: types.sequence[str, 8]
    state: 'spatialdds18.spatial.owm.LifecycleState'
    state_reason: str
    source_id: str
    stamp: 'spatialdds18.spatial.owm.Time'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class ModelPose(idl.IdlStruct, typename="spatial.owm.ModelPose"):
    entity_id: str
    annotate.key("entity_id")
    pose: 'spatialdds18.spatial.owm.PoseSE3'
    source_id: str
    stamp: 'spatialdds18.spatial.owm.Time'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class ModelCommand(idl.IdlStruct, typename="spatial.owm.ModelCommand"):
    command_id: str
    annotate.key("command_id")
    verb: str
    subject_id: str
    reason: str
    requester_id: str
    has_pose: bool
    pose: 'spatialdds18.spatial.owm.PoseSE3'
    has_extent: bool
    extent: 'spatialdds18.spatial.owm.Aabb3'
    stamp: 'spatialdds18.spatial.owm.Time'


