"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: spatial.events.enums.crossing_direction_enum
  IDL file: events.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from spatialdds18 import spatial

@annotate.final
class CrossingDirection(idl.IdlEnum, typename="spatial.events.enums.crossing_direction_enum.CrossingDirection", default="CROSSING_UNKNOWN"):
    CROSSING_UNKNOWN = 0
    LEFT_TO_RIGHT = 1
    RIGHT_TO_LEFT = 2

