"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: spatial.vio
  IDL file: vio.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from spatialdds18 import spatial

if TYPE_CHECKING:
    import builtin
    import spatial.common
    import spatial.core


MODULE_ID = "spatial.vio/1.8"
Time = types.typedef['spatialdds18.spatial.vio.Time', 'spatialdds18.builtin.Time']
FrameRef = types.typedef['spatialdds18.spatial.vio.FrameRef', 'spatialdds18.spatial.common.FrameRef']

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class ImuInfo(idl.IdlStruct, typename="spatial.vio.ImuInfo"):
    imu_id: str
    annotate.key("imu_id")
    frame_ref: 'spatialdds18.spatial.vio.FrameRef'
    accel_noise_density: types.float64
    gyro_noise_density: types.float64
    accel_random_walk: types.float64
    gyro_random_walk: types.float64
    stamp: 'spatialdds18.spatial.vio.Time'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class ImuSample(idl.IdlStruct, typename="spatial.vio.ImuSample"):
    imu_id: str
    annotate.key("imu_id")
    accel: 'spatialdds18.spatial.common.Vec3'
    gyro: 'spatialdds18.spatial.common.Vec3'
    stamp: 'spatialdds18.spatial.vio.Time'
    source_id: str
    seq: types.uint64
    has_accel_cov: bool
    accel_cov: 'spatialdds18.spatial.core.CovMatrix'
    has_gyro_cov: bool
    gyro_cov: 'spatialdds18.spatial.core.CovMatrix'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class MagnetometerSample(idl.IdlStruct, typename="spatial.vio.MagnetometerSample"):
    mag_id: str
    annotate.key("mag_id")
    mag: 'spatialdds18.spatial.common.Vec3'
    stamp: 'spatialdds18.spatial.vio.Time'
    frame_ref: 'spatialdds18.spatial.vio.FrameRef'
    source_id: str
    seq: types.uint64


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class SensorFusionSample(idl.IdlStruct, typename="spatial.vio.SensorFusionSample"):
    fusion_id: str
    annotate.key("fusion_id")
    accel: 'spatialdds18.spatial.common.Vec3'
    gyro: 'spatialdds18.spatial.common.Vec3'
    mag: 'spatialdds18.spatial.common.Vec3'
    stamp: 'spatialdds18.spatial.vio.Time'
    frame_ref: 'spatialdds18.spatial.vio.FrameRef'
    source_id: str
    seq: types.uint64

@annotate.final
class FusionMode(idl.IdlEnum, typename="spatial.vio.FusionMode", default="ORIENTATION_3DOF"):
    ORIENTATION_3DOF = 0
    ORIENTATION_6DOF = 1
    POSE_6DOF = 2
@annotate.final
class FusionSourceKind(idl.IdlEnum, typename="spatial.vio.FusionSourceKind", default="EKF"):
    EKF = 0
    AHRS = 1
    VIO_FUSED = 2
    IMU_ONLY = 3
    MAG_AIDED = 4
    AR_PLATFORM = 5

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class FusedState(idl.IdlStruct, typename="spatial.vio.FusedState"):
    fusion_id: str
    annotate.key("fusion_id")
    mode: 'spatialdds18.spatial.vio.FusionMode'
    source_kind: 'spatialdds18.spatial.vio.FusionSourceKind'
    q: 'spatialdds18.spatial.common.QuaternionXYZW'
    has_position: bool
    t: 'spatialdds18.spatial.common.Vec3'
    has_gravity: bool
    gravity: 'spatialdds18.spatial.common.Vec3'
    has_lin_accel: bool
    lin_accel: 'spatialdds18.spatial.common.Vec3'
    has_gyro_bias: bool
    gyro_bias: 'spatialdds18.spatial.common.Vec3'
    has_accel_bias: bool
    accel_bias: 'spatialdds18.spatial.common.Vec3'
    has_cov_orient: bool
    cov_orient: 'spatialdds18.spatial.common.Mat3x3'
    has_cov_pos: bool
    cov_pos: 'spatialdds18.spatial.common.Mat3x3'
    stamp: 'spatialdds18.spatial.vio.Time'
    frame_ref: 'spatialdds18.spatial.vio.FrameRef'
    source_id: str
    seq: types.uint64
    quality: types.float64


