"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: spatial.mapping
  IDL file: mapping.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from spatialdds18 import spatial

if TYPE_CHECKING:
    import builtin
    import spatial.common
    import spatial.core
    import spatial.mapping.enums.alignment_method
    import spatial.mapping.enums.edge_type
    import spatial.mapping.enums.map_event_kind
    import spatial.mapping.enums.map_kind
    import spatial.mapping.enums.map_status


MODULE_ID = "spatial.mapping/1.8"
Time = types.typedef['spatialdds18.spatial.mapping.Time', 'spatialdds18.builtin.Time']
PoseSE3 = types.typedef['spatialdds18.spatial.mapping.PoseSE3', 'spatialdds18.spatial.core.PoseSE3']
FrameRef = types.typedef['spatialdds18.spatial.mapping.FrameRef', 'spatialdds18.spatial.core.FrameRef']
CovMatrix = types.typedef['spatialdds18.spatial.mapping.CovMatrix', 'spatialdds18.spatial.core.CovMatrix']
BlobRef = types.typedef['spatialdds18.spatial.mapping.BlobRef', 'spatialdds18.spatial.core.BlobRef']
MetaKV = types.typedef['spatialdds18.spatial.mapping.MetaKV', 'spatialdds18.spatial.common.MetaKV']
GeoPose = types.typedef['spatialdds18.spatial.mapping.GeoPose', 'spatialdds18.spatial.core.GeoPose']
MapKind = types.typedef['spatialdds18.spatial.mapping.MapKind', 'spatialdds18.spatial.mapping.enums.map_kind.MapKind']
MapStatus = types.typedef['spatialdds18.spatial.mapping.MapStatus', 'spatialdds18.spatial.mapping.enums.map_status.MapStatus']
EdgeType = types.typedef['spatialdds18.spatial.mapping.EdgeType', 'spatialdds18.spatial.mapping.enums.edge_type.EdgeType']
AlignmentMethod = types.typedef['spatialdds18.spatial.mapping.AlignmentMethod', 'spatialdds18.spatial.mapping.enums.alignment_method.AlignmentMethod']
MapEventKind = types.typedef['spatialdds18.spatial.mapping.MapEventKind', 'spatialdds18.spatial.mapping.enums.map_event_kind.MapEventKind']

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class MapQuality(idl.IdlStruct, typename="spatial.mapping.MapQuality"):
    has_loop_closure_count: bool
    loop_closure_count: types.uint32
    has_mean_residual: bool
    mean_residual: types.float64
    has_max_drift_m: bool
    max_drift_m: types.float64
    has_coverage_pct: bool
    coverage_pct: types.float32
    has_keyframe_count: bool
    keyframe_count: types.uint32
    has_landmark_count: bool
    landmark_count: types.uint32


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class MapMeta(idl.IdlStruct, typename="spatial.mapping.MapMeta"):
    map_id: str
    annotate.key("map_id")
    source_id: str
    annotate.key("source_id")
    kind: 'spatialdds18.spatial.mapping.MapKind'
    status: 'spatialdds18.spatial.mapping.MapStatus'
    algorithm: str
    frame_ref: 'spatialdds18.spatial.mapping.FrameRef'
    has_extent: bool
    extent: 'spatialdds18.spatial.core.Aabb3'
    has_geopose: bool
    geopose: 'spatialdds18.spatial.mapping.GeoPose'
    graph_epoch: types.uint64
    revision: types.uint64
    has_quality: bool
    quality: 'spatialdds18.spatial.mapping.MapQuality'
    created: 'spatialdds18.spatial.mapping.Time'
    stamp: 'spatialdds18.spatial.mapping.Time'
    blob_refs: types.sequence['spatialdds18.spatial.mapping.BlobRef', 32]
    attributes: types.sequence['spatialdds18.spatial.mapping.MetaKV', 32]
    schema_version: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Edge(idl.IdlStruct, typename="spatial.mapping.Edge"):
    map_id: str
    annotate.key("map_id")
    edge_id: str
    annotate.key("edge_id")
    from_id: str
    to_id: str
    type: 'spatialdds18.spatial.mapping.EdgeType'
    T_from_to: 'spatialdds18.spatial.mapping.PoseSE3'
    information: 'spatialdds18.spatial.common.Mat6x6'
    stamp: 'spatialdds18.spatial.mapping.Time'
    source_id: str
    seq: types.uint64
    graph_epoch: types.uint64
    has_from_map_id: bool
    from_map_id: str
    has_to_map_id: bool
    to_map_id: str
    has_match_score: bool
    match_score: types.float32
    has_inlier_count: bool
    inlier_count: types.uint32
    has_range_m: bool
    range_m: types.float32
    has_range_std_m: bool
    range_std_m: types.float32


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class MapAlignment(idl.IdlStruct, typename="spatial.mapping.MapAlignment"):
    alignment_id: str
    annotate.key("alignment_id")
    map_id_from: str
    map_id_to: str
    T_from_to: 'spatialdds18.spatial.mapping.PoseSE3'
    cov: 'spatialdds18.spatial.mapping.CovMatrix'
    method: 'spatialdds18.spatial.mapping.AlignmentMethod'
    stamp: 'spatialdds18.spatial.mapping.Time'
    source_id: str
    has_match_score: bool
    match_score: types.float32
    has_overlap_pct: bool
    overlap_pct: types.float32
    has_supporting_edges: bool
    supporting_edges: types.uint32
    revision: types.uint64
    evidence_edge_ids: types.sequence[str, 64]
    schema_version: str
    has_scale_ratio: bool
    scale_ratio: types.float64


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class MapEvent(idl.IdlStruct, typename="spatial.mapping.MapEvent"):
    map_id: str
    annotate.key("map_id")
    event: 'spatialdds18.spatial.mapping.MapEventKind'
    source_id: str
    stamp: 'spatialdds18.spatial.mapping.Time'
    has_new_status: bool
    new_status: 'spatialdds18.spatial.mapping.MapStatus'
    has_new_epoch: bool
    new_epoch: types.uint64
    has_alignment_id: bool
    alignment_id: str
    has_reason: bool
    reason: str


