"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: spatial.semantics
  IDL file: semantics.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from spatialdds18 import spatial

if TYPE_CHECKING:
    import builtin
    import spatial.common
    import spatial.core


MODULE_ID = "spatial.semantics/1.8"
Time = types.typedef['spatialdds18.spatial.semantics.Time', 'spatialdds18.builtin.Time']
TileKey = types.typedef['spatialdds18.spatial.semantics.TileKey', 'spatialdds18.spatial.core.TileKey']
FrameRef = types.typedef['spatialdds18.spatial.semantics.FrameRef', 'spatialdds18.spatial.common.FrameRef']

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Keypoint3D(idl.IdlStruct, typename="spatial.semantics.Keypoint3D"):
    position: 'spatialdds18.spatial.common.Vec3'
    confidence: types.float32
    has_visible: bool
    visible: bool


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class KeypointLink(idl.IdlStruct, typename="spatial.semantics.KeypointLink"):
    from_index: types.uint16
    to_index: types.uint16


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Detection2D(idl.IdlStruct, typename="spatial.semantics.Detection2D"):
    det_id: str
    annotate.key("det_id")
    node_id: str
    camera_id: str
    class_id: str
    score: types.float32
    bbox: 'spatialdds18.spatial.common.BBox2D'
    has_mask: bool
    mask_blob_id: str
    stamp: 'spatialdds18.spatial.semantics.Time'
    source_id: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Detection2DSet(idl.IdlStruct, typename="spatial.semantics.Detection2DSet"):
    set_id: str
    annotate.key("set_id")
    node_id: str
    camera_id: str
    dets: types.sequence['spatialdds18.spatial.semantics.Detection2D', 256]
    stamp: 'spatialdds18.spatial.semantics.Time'
    source_id: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Detection3D(idl.IdlStruct, typename="spatial.semantics.Detection3D"):
    det_id: str
    annotate.key("det_id")
    frame_ref: 'spatialdds18.spatial.semantics.FrameRef'
    has_tile: bool
    tile_key: 'spatialdds18.spatial.semantics.TileKey'
    class_id: str
    score: types.float32
    center: 'spatialdds18.spatial.common.Vec3'
    size: 'spatialdds18.spatial.common.Vec3'
    q: 'spatialdds18.spatial.common.QuaternionXYZW'
    has_covariance: bool
    cov_pos: 'spatialdds18.spatial.common.Mat3x3'
    cov_rot: 'spatialdds18.spatial.common.Mat3x3'
    has_track_id: bool
    track_id: str
    stamp: 'spatialdds18.spatial.semantics.Time'
    source_id: str
    has_attributes: bool
    attributes: types.sequence['spatialdds18.spatial.common.MetaKV', 8]
    has_visibility: bool
    visibility: types.float32
    has_num_pts: bool
    num_lidar_pts: types.uint32
    num_radar_pts: types.uint32
    has_velocity: bool
    velocity: 'spatialdds18.spatial.common.Vec3'
    has_observer: bool
    observer_position: 'spatialdds18.spatial.common.Vec3'
    observer_cov: 'spatialdds18.spatial.core.CovMatrix'
    has_observer_cov_scope: bool
    observer_cov_scope: 'spatialdds18.spatial.common.CovScope'
    has_keypoints: bool
    keypoints: types.sequence['spatialdds18.spatial.semantics.Keypoint3D', 192]
    topology_id: str
    keypoint_links: types.sequence['spatialdds18.spatial.semantics.KeypointLink', 256]


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Detection3DSet(idl.IdlStruct, typename="spatial.semantics.Detection3DSet"):
    set_id: str
    annotate.key("set_id")
    frame_ref: 'spatialdds18.spatial.semantics.FrameRef'
    has_tile: bool
    tile_key: 'spatialdds18.spatial.semantics.TileKey'
    dets: types.sequence['spatialdds18.spatial.semantics.Detection3D', 256]
    stamp: 'spatialdds18.spatial.semantics.Time'
    source_id: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class FusedTrack(idl.IdlStruct, typename="spatial.semantics.FusedTrack"):
    track_id: str
    object_class: str
    confidence: types.float32
    position: 'spatialdds18.spatial.common.Vec3'
    has_position_cov: bool
    position_cov: 'spatialdds18.spatial.common.Mat3x3'
    has_velocity: bool
    velocity: 'spatialdds18.spatial.common.Vec3'
    has_velocity_cov: bool
    velocity_cov: 'spatialdds18.spatial.common.Mat3x3'
    source_operators: types.sequence[str, 16]
    source_modalities: types.sequence[str, 16]
    source_count: types.uint32
    track_age_s: types.float64
    has_observer_cov: bool
    observer_cov: 'spatialdds18.spatial.core.CovMatrix'
    has_observer_cov_scope: bool
    observer_cov_scope: 'spatialdds18.spatial.common.CovScope'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class FusedTrackSet(idl.IdlStruct, typename="spatial.semantics.FusedTrackSet"):
    stream_id: str
    annotate.key("stream_id")
    schema_version: str
    frame_ref: 'spatialdds18.spatial.semantics.FrameRef'
    tracks: types.sequence['spatialdds18.spatial.semantics.FusedTrack', 256]
    stamp: 'spatialdds18.spatial.semantics.Time'
    source_id: str
    seq: types.uint64


