"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: spatial.events
  IDL file: events.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from spatialdds18 import spatial

if TYPE_CHECKING:
    import builtin
    import spatial.common
    import spatial.core
    import spatial.events.enums.crossing_direction_enum
    import spatial.events.enums.event_state_enum
    import spatial.events.enums.event_type_enum
    import spatial.events.enums.severity_enum
    import spatial.events.enums.zone_kind_enum


MODULE_ID = "spatial.events/1.8"
Time = types.typedef['spatialdds18.spatial.events.Time', 'spatialdds18.builtin.Time']
PoseSE3 = types.typedef['spatialdds18.spatial.events.PoseSE3', 'spatialdds18.spatial.core.PoseSE3']
FrameRef = types.typedef['spatialdds18.spatial.events.FrameRef', 'spatialdds18.spatial.core.FrameRef']
Aabb3 = types.typedef['spatialdds18.spatial.events.Aabb3', 'spatialdds18.spatial.core.Aabb3']
BlobRef = types.typedef['spatialdds18.spatial.events.BlobRef', 'spatialdds18.spatial.core.BlobRef']
GeoPose = types.typedef['spatialdds18.spatial.events.GeoPose', 'spatialdds18.spatial.core.GeoPose']
MetaKV = types.typedef['spatialdds18.spatial.events.MetaKV', 'spatialdds18.spatial.common.MetaKV']
ZoneKind = types.typedef['spatialdds18.spatial.events.ZoneKind', 'spatialdds18.spatial.events.enums.zone_kind_enum.ZoneKind']
EventType = types.typedef['spatialdds18.spatial.events.EventType', 'spatialdds18.spatial.events.enums.event_type_enum.EventType']
Severity = types.typedef['spatialdds18.spatial.events.Severity', 'spatialdds18.spatial.events.enums.severity_enum.Severity']
EventState = types.typedef['spatialdds18.spatial.events.EventState', 'spatialdds18.spatial.events.enums.event_state_enum.EventState']
CrossingDirection = types.typedef['spatialdds18.spatial.events.CrossingDirection', 'spatialdds18.spatial.events.enums.crossing_direction_enum.CrossingDirection']

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class SpatialZone(idl.IdlStruct, typename="spatial.events.SpatialZone"):
    zone_id: str
    annotate.key("zone_id")
    name: str
    kind: 'spatialdds18.spatial.events.ZoneKind'
    frame_ref: 'spatialdds18.spatial.events.FrameRef'
    has_bounds: bool
    bounds: 'spatialdds18.spatial.events.Aabb3'
    has_geopose: bool
    geopose: 'spatialdds18.spatial.events.GeoPose'
    has_speed_limit_mps: bool
    speed_limit_mps: types.float32
    has_capacity: bool
    capacity: types.uint32
    has_dwell_limit_sec: bool
    dwell_limit_sec: types.float32
    class_filter: types.sequence[str, 32]
    has_schedule: bool
    schedule: str
    provider_id: str
    stamp: 'spatialdds18.spatial.events.Time'
    attributes: types.sequence['spatialdds18.spatial.events.MetaKV', 16]
    schema_version: str
    has_polygon: bool
    polygon: types.sequence['spatialdds18.spatial.common.Vec2', 256]
    z_min: types.float64
    z_max: types.float64


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class CrossingLine(idl.IdlStruct, typename="spatial.events.CrossingLine"):
    line_id: str
    annotate.key("line_id")
    name: str
    frame_ref: 'spatialdds18.spatial.events.FrameRef'
    path: types.sequence['spatialdds18.spatial.common.Vec2', 256]
    has_vertical_band: bool
    z_min: types.float64
    z_max: types.float64
    has_bounds: bool
    bounds: 'spatialdds18.spatial.events.Aabb3'
    class_filter: types.sequence[str, 32]
    provider_id: str
    stamp: 'spatialdds18.spatial.events.Time'
    attributes: types.sequence['spatialdds18.spatial.events.MetaKV', 16]
    schema_version: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class SpatialEvent(idl.IdlStruct, typename="spatial.events.SpatialEvent"):
    event_id: str
    annotate.key("event_id")
    type: 'spatialdds18.spatial.events.EventType'
    severity: 'spatialdds18.spatial.events.Severity'
    state: 'spatialdds18.spatial.events.EventState'
    has_zone_id: bool
    zone_id: str
    has_position: bool
    position: 'spatialdds18.spatial.common.Vec3'
    frame_ref: 'spatialdds18.spatial.events.FrameRef'
    has_trigger_det_id: bool
    trigger_det_id: str
    has_trigger_track_id: bool
    trigger_track_id: str
    trigger_class_id: str
    has_secondary_det_id: bool
    secondary_det_id: str
    has_measured_speed_mps: bool
    measured_speed_mps: types.float32
    has_measured_dwell_sec: bool
    measured_dwell_sec: types.float32
    has_measured_distance_m: bool
    measured_distance_m: types.float32
    has_zone_occupancy: bool
    zone_occupancy: types.uint32
    confidence: types.float32
    has_evidence: bool
    evidence: 'spatialdds18.spatial.events.BlobRef'
    has_description: bool
    description: str
    event_start: 'spatialdds18.spatial.events.Time'
    stamp: 'spatialdds18.spatial.events.Time'
    source_id: str
    attributes: types.sequence['spatialdds18.spatial.events.MetaKV', 8]
    schema_version: str
    participant_ids: types.sequence[str, 8]
    has_crossing_line_id: bool
    crossing_line_id: str
    has_crossing: bool
    crossing_direction: 'spatialdds18.spatial.events.CrossingDirection'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class ZoneState(idl.IdlStruct, typename="spatial.events.ZoneState"):
    zone_id: str
    annotate.key("zone_id")
    current_occupancy: types.uint32
    has_capacity: bool
    capacity: types.uint32
    active_info: types.uint32
    active_warning: types.uint32
    active_alert: types.uint32
    active_critical: types.uint32
    class_counts: types.sequence['spatialdds18.spatial.events.MetaKV', 8]
    stamp: 'spatialdds18.spatial.events.Time'
    source_id: str


