"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: spatial.sensing.rad
  IDL file: rad.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from spatialdds18 import spatial

if TYPE_CHECKING:
    import builtin
    import spatial.common
    import spatial.core
    import spatial.sensing.common


MODULE_ID = "spatial.sensing.rad/1.8"
Time = types.typedef['spatialdds18.spatial.sensing.rad.Time', 'spatialdds18.builtin.Time']
PoseSE3 = types.typedef['spatialdds18.spatial.sensing.rad.PoseSE3', 'spatialdds18.spatial.core.PoseSE3']
BlobRef = types.typedef['spatialdds18.spatial.sensing.rad.BlobRef', 'spatialdds18.spatial.core.BlobRef']
FrameRef = types.typedef['spatialdds18.spatial.sensing.rad.FrameRef', 'spatialdds18.spatial.common.FrameRef']
Codec = types.typedef['spatialdds18.spatial.sensing.rad.Codec', 'spatialdds18.spatial.sensing.common.Codec']
StreamMeta = types.typedef['spatialdds18.spatial.sensing.rad.StreamMeta', 'spatialdds18.spatial.sensing.common.StreamMeta']
FrameHeader = types.typedef['spatialdds18.spatial.sensing.rad.FrameHeader', 'spatialdds18.spatial.sensing.common.FrameHeader']
FrameQuality = types.typedef['spatialdds18.spatial.sensing.rad.FrameQuality', 'spatialdds18.spatial.sensing.common.FrameQuality']
Axis = types.typedef['spatialdds18.spatial.sensing.rad.Axis', 'spatialdds18.spatial.sensing.common.Axis']
SampleType = types.typedef['spatialdds18.spatial.sensing.rad.SampleType', 'spatialdds18.spatial.sensing.common.SampleType']
PayloadKind = types.typedef['spatialdds18.spatial.sensing.rad.PayloadKind', 'spatialdds18.spatial.sensing.common.PayloadKind']
ROI = types.typedef['spatialdds18.spatial.sensing.rad.ROI', 'spatialdds18.spatial.sensing.common.ROI']
ROIRequest = types.typedef['spatialdds18.spatial.sensing.rad.ROIRequest', 'spatialdds18.spatial.sensing.common.ROIRequest']
ROIReply = types.typedef['spatialdds18.spatial.sensing.rad.ROIReply', 'spatialdds18.spatial.sensing.common.ROIReply']
@annotate.final
class RadSensorType(idl.IdlEnum, typename="spatial.sensing.rad.RadSensorType", default="SHORT_RANGE"):
    SHORT_RANGE = 0
    MEDIUM_RANGE = 1
    LONG_RANGE = 2
    IMAGING_4D = 3
    SAR = 4
    OTHER = 255
@annotate.final
class RadDynProp(idl.IdlEnum, typename="spatial.sensing.rad.RadDynProp", default="UNKNOWN"):
    UNKNOWN = 0
    MOVING = 1
    STATIONARY = 2
    ONCOMING = 3
    CROSSING_LEFT = 4
    CROSSING_RIGHT = 5
    STOPPED = 6

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class RadSensorMeta(idl.IdlStruct, typename="spatial.sensing.rad.RadSensorMeta"):
    stream_id: str
    annotate.key("stream_id")
    base: 'spatialdds18.spatial.sensing.rad.StreamMeta'
    sensor_type: 'spatialdds18.spatial.sensing.rad.RadSensorType'
    has_range_limits: bool
    min_range_m: types.float32
    max_range_m: types.float32
    has_azimuth_fov: bool
    az_fov_min_deg: types.float32
    az_fov_max_deg: types.float32
    has_elevation_fov: bool
    el_fov_min_deg: types.float32
    el_fov_max_deg: types.float32
    has_velocity_limits: bool
    v_min_mps: types.float32
    v_max_mps: types.float32
    max_detections_per_frame: types.uint32
    proc_chain: str
    schema_version: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class RadDetection(idl.IdlStruct, typename="spatial.sensing.rad.RadDetection"):
    xyz_m: 'spatialdds18.spatial.common.Vec3'
    has_velocity_xyz: bool
    velocity_xyz: 'spatialdds18.spatial.common.Vec3'
    has_v_r_mps: bool
    v_r_mps: types.float64
    has_velocity_comp_xyz: bool
    velocity_comp_xyz: 'spatialdds18.spatial.common.Vec3'
    has_rcs_dbm2: bool
    rcs_dbm2: types.float32
    intensity: types.float32
    quality: types.float32
    has_dyn_prop: bool
    dyn_prop: 'spatialdds18.spatial.sensing.rad.RadDynProp'
    has_pos_rms: bool
    x_rms_m: types.float32
    y_rms_m: types.float32
    z_rms_m: types.float32
    has_vel_rms: bool
    vx_rms_mps: types.float32
    vy_rms_mps: types.float32
    vz_rms_mps: types.float32
    has_ambig_state: bool
    ambig_state: types.uint8
    has_false_alarm_prob: bool
    false_alarm_prob: types.float32
    has_sensor_track_id: bool
    sensor_track_id: types.uint32


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class RadDetectionSet(idl.IdlStruct, typename="spatial.sensing.rad.RadDetectionSet"):
    stream_id: str
    annotate.key("stream_id")
    frame_seq: types.uint64
    frame_ref: 'spatialdds18.spatial.sensing.rad.FrameRef'
    dets: types.sequence['spatialdds18.spatial.sensing.rad.RadDetection', 32768]
    stamp: 'spatialdds18.spatial.sensing.rad.Time'
    source_id: str
    seq: types.uint64
    proc_chain: str
    has_quality: bool
    quality: 'spatialdds18.spatial.sensing.rad.FrameQuality'

@annotate.final
class RadTensorLayout(idl.IdlEnum, typename="spatial.sensing.rad.RadTensorLayout", default="RA_D"):
    RA_D = 0
    R_AZ_EL_D = 1
    CH_FAST_SLOW = 2
    CH_R_D = 3
    CUSTOM = 255

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class RadTensorMeta(idl.IdlStruct, typename="spatial.sensing.rad.RadTensorMeta"):
    stream_id: str
    annotate.key("stream_id")
    base: 'spatialdds18.spatial.sensing.rad.StreamMeta'
    sensor_type: 'spatialdds18.spatial.sensing.rad.RadSensorType'
    layout: 'spatialdds18.spatial.sensing.rad.RadTensorLayout'
    axes: types.sequence['spatialdds18.spatial.sensing.rad.Axis', 8]
    voxel_type: 'spatialdds18.spatial.sensing.rad.SampleType'
    physical_meaning: str
    has_antenna_config: bool
    num_tx: types.uint16
    num_rx: types.uint16
    num_virtual_channels: types.uint16
    has_waveform_params: bool
    bandwidth_hz: types.float32
    center_freq_hz: types.float32
    chirp_duration_s: types.float32
    samples_per_chirp: types.uint32
    chirps_per_frame: types.uint32
    payload_kind: 'spatialdds18.spatial.sensing.rad.PayloadKind'
    codec: 'spatialdds18.spatial.sensing.rad.Codec'
    has_quant_scale: bool
    quant_scale: types.float32
    tile_size: types.array[types.uint32, 4]
    schema_version: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class RadTensorFrame(idl.IdlStruct, typename="spatial.sensing.rad.RadTensorFrame"):
    stream_id: str
    annotate.key("stream_id")
    frame_seq: types.uint64
    hdr: 'spatialdds18.spatial.sensing.rad.FrameHeader'
    payload_kind: 'spatialdds18.spatial.sensing.rad.PayloadKind'
    codec: 'spatialdds18.spatial.sensing.rad.Codec'
    voxel_type_after_decode: 'spatialdds18.spatial.sensing.rad.SampleType'
    has_quant_scale: bool
    quant_scale: types.float32
    quality: 'spatialdds18.spatial.sensing.rad.FrameQuality'
    proc_chain: str


