# Generated by tools/generate_bindings.py, do not edit.
#   regenerate: python3 tools/generate_bindings.py

"""Generated SpatialDDS 1.8 types. See tools/generate_bindings.py."""

from . import builtin
from . import spatial

__all__ = ["builtin", "spatial"]
