# Generated by scripts/generate_types_18.py — do not edit.
#   regenerate: python3 scripts/generate_types_18.py

"""Generated SpatialDDS 1.8 types. See scripts/generate_types_18.py."""

from . import builtin
from . import spatial

__all__ = ["builtin", "spatial"]
