# Generated by tools/generate_bindings.py, do not edit.
#   regenerate: python3 tools/generate_bindings.py


"""Python attribute -> IDL field name, for fields renamed to dodge
Python keywords. See fix_python_keyword_fields in the generator."""

FIELD_ALIASES = {
    "spatial.disco.CoverageElement": {
        "_global": "global",
    },
    "spatial.disco.Transform": {
        "_from": "from",
    },
    "spatial.disco.ValidityWindow": {
        "_from": "from",
    },
    "spatial.sensing.common.ROI": {
        "_global": "global",
    },
}


def wire_name(typename: str, attr: str) -> str:
    """The IDL field name for a generated attribute."""
    return FIELD_ALIASES.get(typename, {}).get(attr, attr)
