"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: spatial.sensing.vision
  IDL file: vision.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from spatialdds18 import spatial

if TYPE_CHECKING:
    import builtin
    import spatial.common
    import spatial.core
    import spatial.sensing.common


MODULE_ID = "spatial.sensing.vision/1.8"
Time = types.typedef['spatialdds18.spatial.sensing.vision.Time', 'spatialdds18.builtin.Time']
PoseSE3 = types.typedef['spatialdds18.spatial.sensing.vision.PoseSE3', 'spatialdds18.spatial.core.PoseSE3']
BlobRef = types.typedef['spatialdds18.spatial.sensing.vision.BlobRef', 'spatialdds18.spatial.core.BlobRef']
FrameRef = types.typedef['spatialdds18.spatial.sensing.vision.FrameRef', 'spatialdds18.spatial.common.FrameRef']
Codec = types.typedef['spatialdds18.spatial.sensing.vision.Codec', 'spatialdds18.spatial.sensing.common.Codec']
PayloadKind = types.typedef['spatialdds18.spatial.sensing.vision.PayloadKind', 'spatialdds18.spatial.sensing.common.PayloadKind']
SampleType = types.typedef['spatialdds18.spatial.sensing.vision.SampleType', 'spatialdds18.spatial.sensing.common.SampleType']
Axis = types.typedef['spatialdds18.spatial.sensing.vision.Axis', 'spatialdds18.spatial.sensing.common.Axis']
ROI = types.typedef['spatialdds18.spatial.sensing.vision.ROI', 'spatialdds18.spatial.sensing.common.ROI']
StreamMeta = types.typedef['spatialdds18.spatial.sensing.vision.StreamMeta', 'spatialdds18.spatial.sensing.common.StreamMeta']
FrameHeader = types.typedef['spatialdds18.spatial.sensing.vision.FrameHeader', 'spatialdds18.spatial.sensing.common.FrameHeader']
FrameQuality = types.typedef['spatialdds18.spatial.sensing.vision.FrameQuality', 'spatialdds18.spatial.sensing.common.FrameQuality']
ROIRequest = types.typedef['spatialdds18.spatial.sensing.vision.ROIRequest', 'spatialdds18.spatial.sensing.common.ROIRequest']
ROIReply = types.typedef['spatialdds18.spatial.sensing.vision.ROIReply', 'spatialdds18.spatial.sensing.common.ROIReply']
@annotate.final
class CamModel(idl.IdlEnum, typename="spatial.sensing.vision.CamModel", default="PINHOLE"):
    PINHOLE = 0
    FISHEYE_EQUIDISTANT = 1
    KB_4 = 2
    OMNI = 3
@annotate.final
class Distortion(idl.IdlEnum, typename="spatial.sensing.vision.Distortion", default="NONE"):
    NONE = 0
    RADTAN = 1
    KANNALA_BRANDT = 2
@annotate.final
class PixFormat(idl.IdlEnum, typename="spatial.sensing.vision.PixFormat", default="UNKNOWN"):
    UNKNOWN = 0
    YUV420 = 1
    RGB8 = 2
    BGR8 = 3
    RGBA8 = 4
    DEPTH16 = 5
    RAW10 = 10
    RAW12 = 12
    RAW16 = 16
@annotate.final
class ColorSpace(idl.IdlEnum, typename="spatial.sensing.vision.ColorSpace", default="SRGB"):
    SRGB = 0
    REC709 = 1
    REC2020 = 2
    LINEAR = 10
@annotate.final
class RigRole(idl.IdlEnum, typename="spatial.sensing.vision.RigRole", default="LEFT"):
    LEFT = 0
    RIGHT = 1
    CENTER = 2
    FRONT = 3
    FRONT_LEFT = 4
    FRONT_RIGHT = 5
    BACK = 6
    BACK_LEFT = 7
    BACK_RIGHT = 8
    AUX = 9
    PANORAMIC = 10
    EQUIRECTANGULAR = 11

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class CamIntrinsics(idl.IdlStruct, typename="spatial.sensing.vision.CamIntrinsics"):
    model: 'spatialdds18.spatial.sensing.vision.CamModel'
    width: types.uint16
    height: types.uint16
    fx: types.float32
    fy: types.float32
    cx: types.float32
    cy: types.float32
    dist: 'spatialdds18.spatial.sensing.vision.Distortion'
    dist_params: types.sequence[types.float32, 16]
    shutter_us: types.float32
    readout_us: types.float32
    pix: 'spatialdds18.spatial.sensing.vision.PixFormat'
    color: 'spatialdds18.spatial.sensing.vision.ColorSpace'
    calib_version: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class VisionMeta(idl.IdlStruct, typename="spatial.sensing.vision.VisionMeta"):
    stream_id: str
    annotate.key("stream_id")
    base: 'spatialdds18.spatial.sensing.vision.StreamMeta'
    K: 'spatialdds18.spatial.sensing.vision.CamIntrinsics'
    role: 'spatialdds18.spatial.sensing.vision.RigRole'
    rig_id: str
    codec: 'spatialdds18.spatial.sensing.vision.Codec'
    pix: 'spatialdds18.spatial.sensing.vision.PixFormat'
    color: 'spatialdds18.spatial.sensing.vision.ColorSpace'
    schema_version: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class VisionFrame(idl.IdlStruct, typename="spatial.sensing.vision.VisionFrame"):
    stream_id: str
    annotate.key("stream_id")
    frame_seq: types.uint64
    hdr: 'spatialdds18.spatial.sensing.vision.FrameHeader'
    codec: 'spatialdds18.spatial.sensing.vision.Codec'
    pix: 'spatialdds18.spatial.sensing.vision.PixFormat'
    color: 'spatialdds18.spatial.sensing.vision.ColorSpace'
    has_line_readout_us: bool
    line_readout_us: types.float32
    rectified: bool
    is_key_frame: bool
    quality: 'spatialdds18.spatial.sensing.vision.FrameQuality'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Keypoint2D(idl.IdlStruct, typename="spatial.sensing.vision.Keypoint2D"):
    u: types.float32
    v: types.float32
    score: types.float32


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Track2D(idl.IdlStruct, typename="spatial.sensing.vision.Track2D"):
    id: types.uint64
    trail: types.sequence['spatialdds18.spatial.sensing.vision.Keypoint2D', 8192]


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class VisionDetections(idl.IdlStruct, typename="spatial.sensing.vision.VisionDetections"):
    stream_id: str
    annotate.key("stream_id")
    frame_seq: types.uint64
    stamp: 'spatialdds18.spatial.sensing.vision.Time'
    keypoints: types.sequence['spatialdds18.spatial.sensing.vision.Keypoint2D', 8192]
    tracks: types.sequence['spatialdds18.spatial.sensing.vision.Track2D', 2048]


