"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: spatial.sensing.rf_beam
  IDL file: rf_beam.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from spatialdds18 import spatial

if TYPE_CHECKING:
    import builtin
    import spatial.common
    import spatial.core
    import spatial.sensing.common


MODULE_ID = "spatial.sensing.rf_beam/1.8"
Time = types.typedef['spatialdds18.spatial.sensing.rf_beam.Time', 'spatialdds18.builtin.Time']
PoseSE3 = types.typedef['spatialdds18.spatial.sensing.rf_beam.PoseSE3', 'spatialdds18.spatial.core.PoseSE3']
BlobRef = types.typedef['spatialdds18.spatial.sensing.rf_beam.BlobRef', 'spatialdds18.spatial.core.BlobRef']
FrameRef = types.typedef['spatialdds18.spatial.sensing.rf_beam.FrameRef', 'spatialdds18.spatial.common.FrameRef']
StreamMeta = types.typedef['spatialdds18.spatial.sensing.rf_beam.StreamMeta', 'spatialdds18.spatial.sensing.common.StreamMeta']
FrameHeader = types.typedef['spatialdds18.spatial.sensing.rf_beam.FrameHeader', 'spatialdds18.spatial.sensing.common.FrameHeader']
FrameQuality = types.typedef['spatialdds18.spatial.sensing.rf_beam.FrameQuality', 'spatialdds18.spatial.sensing.common.FrameQuality']
Codec = types.typedef['spatialdds18.spatial.sensing.rf_beam.Codec', 'spatialdds18.spatial.sensing.common.Codec']
SampleType = types.typedef['spatialdds18.spatial.sensing.rf_beam.SampleType', 'spatialdds18.spatial.sensing.common.SampleType']
@annotate.final
class BeamSweepType(idl.IdlEnum, typename="spatial.sensing.rf_beam.BeamSweepType", default="EXHAUSTIVE"):
    EXHAUSTIVE = 0
    HIERARCHICAL = 1
    TRACKING = 2
    PARTIAL = 3
    OTHER = 255
@annotate.final
class PowerUnit(idl.IdlEnum, typename="spatial.sensing.rf_beam.PowerUnit", default="DBM"):
    DBM = 0
    LINEAR_MW = 1
    RSRP = 2
    OTHER_UNIT = 255

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class RfBeamMeta(idl.IdlStruct, typename="spatial.sensing.rf_beam.RfBeamMeta"):
    stream_id: str
    annotate.key("stream_id")
    base: 'spatialdds18.spatial.sensing.rf_beam.StreamMeta'
    center_freq_ghz: types.float32
    has_bandwidth: bool
    bandwidth_ghz: types.float32
    n_elements: types.uint16
    n_beams: types.uint16
    fov_az_deg: types.float32
    has_fov_el: bool
    fov_el_deg: types.float32
    has_array_index: bool
    array_index: types.uint8
    array_label: str
    codebook_type: str
    has_mimo_config: bool
    n_tx: types.uint16
    n_rx: types.uint16
    power_unit: 'spatialdds18.spatial.sensing.rf_beam.PowerUnit'
    schema_version: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class RfBeamFrame(idl.IdlStruct, typename="spatial.sensing.rf_beam.RfBeamFrame"):
    stream_id: str
    annotate.key("stream_id")
    frame_seq: types.uint64
    hdr: 'spatialdds18.spatial.sensing.rf_beam.FrameHeader'
    sweep_type: 'spatialdds18.spatial.sensing.rf_beam.BeamSweepType'
    power: types.sequence[types.float32, 1024]
    beam_indices: types.sequence[types.uint16, 1024]
    has_best_beam: bool
    best_beam_idx: types.uint16
    best_beam_power: types.float32
    has_blockage_state: bool
    is_blocked: bool
    blockage_confidence: types.float32
    has_snr_db: bool
    snr_db: types.float32
    has_quality: bool
    quality: 'spatialdds18.spatial.sensing.rf_beam.FrameQuality'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class RfBeamArraySet(idl.IdlStruct, typename="spatial.sensing.rf_beam.RfBeamArraySet"):
    set_id: str
    annotate.key("set_id")
    frame_seq: types.uint64
    stamp: 'spatialdds18.spatial.sensing.rf_beam.Time'
    arrays: types.sequence['spatialdds18.spatial.sensing.rf_beam.RfBeamFrame', 8]
    has_overall_best: bool
    overall_best_array_idx: types.uint16
    overall_best_beam_idx: types.uint16
    overall_best_power: types.float32


