"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: spatial.sensing.lidar
  IDL file: lidar.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from spatialdds18 import spatial

if TYPE_CHECKING:
    import builtin
    import spatial.common
    import spatial.core
    import spatial.sensing.common


MODULE_ID = "spatial.sensing.lidar/1.8"
Time = types.typedef['spatialdds18.spatial.sensing.lidar.Time', 'spatialdds18.builtin.Time']
PoseSE3 = types.typedef['spatialdds18.spatial.sensing.lidar.PoseSE3', 'spatialdds18.spatial.core.PoseSE3']
BlobRef = types.typedef['spatialdds18.spatial.sensing.lidar.BlobRef', 'spatialdds18.spatial.core.BlobRef']
FrameRef = types.typedef['spatialdds18.spatial.sensing.lidar.FrameRef', 'spatialdds18.spatial.common.FrameRef']
Codec = types.typedef['spatialdds18.spatial.sensing.lidar.Codec', 'spatialdds18.spatial.sensing.common.Codec']
PayloadKind = types.typedef['spatialdds18.spatial.sensing.lidar.PayloadKind', 'spatialdds18.spatial.sensing.common.PayloadKind']
SampleType = types.typedef['spatialdds18.spatial.sensing.lidar.SampleType', 'spatialdds18.spatial.sensing.common.SampleType']
Axis = types.typedef['spatialdds18.spatial.sensing.lidar.Axis', 'spatialdds18.spatial.sensing.common.Axis']
ROI = types.typedef['spatialdds18.spatial.sensing.lidar.ROI', 'spatialdds18.spatial.sensing.common.ROI']
StreamMeta = types.typedef['spatialdds18.spatial.sensing.lidar.StreamMeta', 'spatialdds18.spatial.sensing.common.StreamMeta']
FrameHeader = types.typedef['spatialdds18.spatial.sensing.lidar.FrameHeader', 'spatialdds18.spatial.sensing.common.FrameHeader']
FrameQuality = types.typedef['spatialdds18.spatial.sensing.lidar.FrameQuality', 'spatialdds18.spatial.sensing.common.FrameQuality']
ROIRequest = types.typedef['spatialdds18.spatial.sensing.lidar.ROIRequest', 'spatialdds18.spatial.sensing.common.ROIRequest']
ROIReply = types.typedef['spatialdds18.spatial.sensing.lidar.ROIReply', 'spatialdds18.spatial.sensing.common.ROIReply']
@annotate.final
class LidarType(idl.IdlEnum, typename="spatial.sensing.lidar.LidarType", default="SPINNING_2D"):
    SPINNING_2D = 0
    MULTI_BEAM_3D = 1
    SOLID_STATE = 2
@annotate.final
class CloudEncoding(idl.IdlEnum, typename="spatial.sensing.lidar.CloudEncoding", default="PCD"):
    PCD = 0
    PLY = 1
    LAS = 2
    LAZ = 3
    BIN_INTERLEAVED = 4
    GLTF_DRACO = 10
    MPEG_PCC = 20
    CUSTOM_BIN = 255
@annotate.final
class PointLayout(idl.IdlEnum, typename="spatial.sensing.lidar.PointLayout", default="XYZ_I"):
    XYZ_I = 0
    XYZ_I_R = 1
    XYZ_I_R_N = 2
    XYZ_I_R_T = 3
    XYZ_I_R_T_N = 4

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class LidarMeta(idl.IdlStruct, typename="spatial.sensing.lidar.LidarMeta"):
    stream_id: str
    annotate.key("stream_id")
    base: 'spatialdds18.spatial.sensing.lidar.StreamMeta'
    type: 'spatialdds18.spatial.sensing.lidar.LidarType'
    n_rings: types.uint16
    has_range_limits: bool
    min_range_m: types.float32
    max_range_m: types.float32
    has_horiz_fov: bool
    horiz_fov_deg_min: types.float32
    horiz_fov_deg_max: types.float32
    has_vert_fov: bool
    vert_fov_deg_min: types.float32
    vert_fov_deg_max: types.float32
    has_wavelength: bool
    wavelength_nm: types.float32
    encoding: 'spatialdds18.spatial.sensing.lidar.CloudEncoding'
    codec: 'spatialdds18.spatial.sensing.lidar.Codec'
    layout: 'spatialdds18.spatial.sensing.lidar.PointLayout'
    schema_version: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class LidarFrame(idl.IdlStruct, typename="spatial.sensing.lidar.LidarFrame"):
    stream_id: str
    annotate.key("stream_id")
    frame_seq: types.uint64
    hdr: 'spatialdds18.spatial.sensing.lidar.FrameHeader'
    encoding: 'spatialdds18.spatial.sensing.lidar.CloudEncoding'
    codec: 'spatialdds18.spatial.sensing.lidar.Codec'
    layout: 'spatialdds18.spatial.sensing.lidar.PointLayout'
    has_per_point_timestamps: bool
    has_average_range_m: bool
    average_range_m: types.float32
    has_percent_valid: bool
    percent_valid: types.float32
    has_quality: bool
    quality: 'spatialdds18.spatial.sensing.lidar.FrameQuality'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class LidarDetection(idl.IdlStruct, typename="spatial.sensing.lidar.LidarDetection"):
    xyz_m: 'spatialdds18.spatial.common.Vec3'
    intensity: types.float32
    ring: types.uint16
    quality: types.float32


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class LidarDetectionSet(idl.IdlStruct, typename="spatial.sensing.lidar.LidarDetectionSet"):
    stream_id: str
    annotate.key("stream_id")
    frame_seq: types.uint64
    frame_ref: 'spatialdds18.spatial.sensing.lidar.FrameRef'
    dets: types.sequence['spatialdds18.spatial.sensing.lidar.LidarDetection', 256]
    stamp: 'spatialdds18.spatial.sensing.lidar.Time'


