"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: spatial.common
  IDL file: types.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from spatialdds18 import spatial

BBox2D = types.typedef['spatialdds18.spatial.common.BBox2D', types.array[types.float64, 4]]
Aabb3D = types.typedef['spatialdds18.spatial.common.Aabb3D', types.array[types.float64, 6]]
Vec3 = types.typedef['spatialdds18.spatial.common.Vec3', types.array[types.float64, 3]]
Mat3x3 = types.typedef['spatialdds18.spatial.common.Mat3x3', types.array[types.float64, 9]]
Mat6x6 = types.typedef['spatialdds18.spatial.common.Mat6x6', types.array[types.float64, 36]]
Mat12x12 = types.typedef['spatialdds18.spatial.common.Mat12x12', types.array[types.float64, 144]]
QuaternionXYZW = types.typedef['spatialdds18.spatial.common.QuaternionXYZW', types.array[types.float64, 4]]

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Vec2(idl.IdlStruct, typename="spatial.common.Vec2"):
    x: types.float64
    y: types.float64

@annotate.final
class CovarianceType(idl.IdlEnum, typename="spatial.common.CovarianceType", default="COV_NONE"):
    COV_NONE = 0
    COV_POS3 = 3
    COV_POSE6 = 6
    COV_ROT3 = 9
    COV_POSE6_TWIST6 = 12
@annotate.final
class CoordConvention(idl.IdlEnum, typename="spatial.common.CoordConvention", default="ENU"):
    ENU = 0
    CV = 1
    GRAPHICS = 2
    UNITY_LH = 3
    NED = 4
    OTHER = 5
@annotate.final
class ScaleStatus(idl.IdlEnum, typename="spatial.common.ScaleStatus", default="SCALE_UNKNOWN"):
    SCALE_UNKNOWN = 0
    SCALE_DECLARED = 1
    SCALE_DERIVED = 2
@annotate.final
class CovScope(idl.IdlEnum, typename="spatial.common.CovScope", default="COV_SCOPE_LOCAL"):
    COV_SCOPE_LOCAL = 0
    COV_SCOPE_COMPOSED = 1

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class FrameRef(idl.IdlStruct, typename="spatial.common.FrameRef"):
    uuid: str
    fqn: str
    has_coord_convention: bool
    coord_convention: 'spatialdds18.spatial.common.CoordConvention'
    has_scale: bool
    scale_status: 'spatialdds18.spatial.common.ScaleStatus'
    meters_per_unit: types.float64
    display_unit: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class KV(idl.IdlStruct, typename="spatial.common.KV"):
    key: str
    value: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class MetaKV(idl.IdlStruct, typename="spatial.common.MetaKV"):
    namespace: str
    json: str
    entries: types.sequence['spatialdds18.spatial.common.KV', 64]


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class AssetRef(idl.IdlStruct, typename="spatial.common.AssetRef"):
    uri: str
    media_type: str
    hash: str
    meta: types.sequence['spatialdds18.spatial.common.MetaKV', 16]


