"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: spatial.argeo
  IDL file: argeo.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from spatialdds18 import spatial

if TYPE_CHECKING:
    import builtin
    import spatial.common
    import spatial.core


MODULE_ID = "spatial.argeo/1.8"
Time = types.typedef['spatialdds18.spatial.argeo.Time', 'spatialdds18.builtin.Time']
PoseSE3 = types.typedef['spatialdds18.spatial.argeo.PoseSE3', 'spatialdds18.spatial.core.PoseSE3']
FramedPose = types.typedef['spatialdds18.spatial.argeo.FramedPose', 'spatialdds18.spatial.core.FramedPose']
GeoPose = types.typedef['spatialdds18.spatial.argeo.GeoPose', 'spatialdds18.spatial.core.GeoPose']
CovMatrix = types.typedef['spatialdds18.spatial.argeo.CovMatrix', 'spatialdds18.spatial.core.CovMatrix']
FrameRef = types.typedef['spatialdds18.spatial.argeo.FrameRef', 'spatialdds18.spatial.common.FrameRef']

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class NodeGeo(idl.IdlStruct, typename="spatial.argeo.NodeGeo"):
    map_id: str
    node_id: str
    annotate.key("node_id")
    poses: types.sequence['spatialdds18.spatial.argeo.FramedPose', 8]
    has_geopose: bool
    geopose: 'spatialdds18.spatial.argeo.GeoPose'
    source_id: str
    seq: types.uint64
    graph_epoch: types.uint64


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class QualityRequirements(idl.IdlStruct, typename="spatial.argeo.QualityRequirements"):
    max_rmse_m: types.float64
    min_confidence: types.float64

@annotate.final
class VpsStatus(idl.IdlEnum, typename="spatial.argeo.VpsStatus", default="VPS_SUCCESS"):
    VPS_SUCCESS = 0
    VPS_DEGRADED = 1
    VPS_FAILED = 2

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class VpsRequest(idl.IdlStruct, typename="spatial.argeo.VpsRequest"):
    query_id: str
    annotate.key("query_id")
    service_id: str
    client_frame_ref: 'spatialdds18.spatial.argeo.FrameRef'
    has_prior_geopose: bool
    prior_geopose: 'spatialdds18.spatial.argeo.GeoPose'
    query_blobs: types.sequence['spatialdds18.spatial.core.BlobRef', 8]
    query_stream_id: str
    has_quality_requirements: bool
    quality_requirements: 'spatialdds18.spatial.argeo.QualityRequirements'
    stamp: 'spatialdds18.spatial.argeo.Time'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class VpsResponse(idl.IdlStruct, typename="spatial.argeo.VpsResponse"):
    query_id: str
    annotate.key("query_id")
    service_id: str
    status: 'spatialdds18.spatial.argeo.VpsStatus'
    has_node_geo: bool
    node_geo: 'spatialdds18.spatial.argeo.NodeGeo'
    confidence: types.float64
    has_rmse_m: bool
    rmse_m: types.float64
    stamp: 'spatialdds18.spatial.argeo.Time'


