#!/usr/bin/env python3
"""Generate SpatialDDS **1.8** Python bindings for the SceneScape sidecar.

Runs ``idlc -l py`` over a SpatialDDS spec checkout's ``idl/v1.8/`` and
post-processes the output into an importable package.

Why this file is a copy
-----------------------
``fix_union_discriminators``, ``fix_python_keyword_fields``,
``write_field_aliases`` and ``nest_packages`` below are copied, with only
docstring and version-string edits, from:

    SpatialDDS-demo  scripts/generate_types.py
    at commit e0fd7d29c9ce36d19a57b80eec31dd8dc6392f87
    (that file last touched in db1f264, 2026-09-04)

The obvious alternative was to add an ``--idl-dir``/``--package`` flag to the
demo repo's generator and call it. That was ruled out deliberately: the demo
repo is frozen for ISMAR so that no commit to it needs case-by-case safety
adjudication this month, and an additive flag with a ``--check`` proof is
still a commit.

**Post-ISMAR:** unify these two generators behind an ``--idl-dir`` /
``--package`` flag on the demo repo's script and delete this copy. Until then,
a fix to a copied function must be applied in both places; they are listed
above so the second place is findable.

Why post-processing is needed at all
------------------------------------
Raw ``idlc -l py`` output **compiles but does not import**. Measured on the
1.8 tree at spec ``d612c4c``: all 14 files generate, and then every module
fails with ``name 'CovarianceType' is not defined``, idlc emits union
discriminators as unresolvable bare names. "It compiles" is therefore not a
useful gate, which is why this build's gate is *imports clean plus a
round-trip encode/decode per module* (see ``gates/bindings_roundtrip.py``).
"""
from __future__ import annotations

import argparse
import keyword
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
SIDECAR = HERE.parent
# The IDL ships in this repository, so the default needs no sibling
# checkout. Point --spec at a SpatialDDS-spec clone to generate from a
# different revision.
DEFAULT_SPEC = SIDECAR
DEFAULT_OUT = SIDECAR / "spatialdds18"
PACKAGE = "spatialdds18"

HEADER = (
    "# Generated by tools/generate_bindings.py, do not edit.\n"
    "#   regenerate: python3 tools/generate_bindings.py\n\n"
)


def run_idlc(spec_idl: Path, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    # The stable profiles, plus the provisional modules one directory down.
    # Provisional modules are independently versioned and exempt from the 1.x
    # additive guarantee, so they are compiled from the same pinned tree but
    # named separately in idl/PROVENANCE by content digest: a recording made
    # against spatial.owm/0.1 has to be able to say which 0.1 it meant.
    files = sorted(spec_idl.glob("*.idl"))
    files += sorted((spec_idl / "provisional").glob("*.idl"))
    if not files:
        raise SystemExit(f"no .idl files in {spec_idl}")
    for f in files:
        r = subprocess.run(
            ["idlc", "-l", "py", "-I", str(spec_idl),
             "-I", str(spec_idl / "provisional"), str(f)],
            cwd=out_dir, capture_output=True, text=True)
        if r.returncode != 0:
            raise SystemExit(f"idlc failed on {f.name}:\n{r.stderr}")


# ---------------------------------------------------------------------------
# Copied from SpatialDDS-demo scripts/generate_types.py @ e0fd7d2, see header.
# ---------------------------------------------------------------------------

def _defined_names(source: str) -> set[str]:
    return set(re.findall(r"^class (\w+)", source, re.M))


def _index_definitions(root: Path, package: str) -> dict[str, str]:
    index: dict[str, str] = {}
    for path in sorted(root.rglob("*.py")):
        parts = path.relative_to(root).with_suffix("").parts
        module = ".".join((package, *parts))
        for name in _defined_names(path.read_text()):
            index.setdefault(name, module)
    return index


def nest_packages(staging: Path, out_dir: Path, package: str) -> None:
    """Move idlc's top-level packages under one package and fix their imports."""
    out_dir.mkdir(parents=True, exist_ok=True)
    roots = sorted(d.name for d in staging.iterdir()
                   if d.is_dir() and (d / "__init__.py").exists())
    if not roots:
        raise SystemExit(f"idlc produced no packages in {staging}")
    for root in roots:
        shutil.move(str(staging / root), str(out_dir / root))

    import_re = re.compile(r"^import (%s)$" % "|".join(roots), re.M)
    # Quoted forward refs ('spatial.common.Mat3x3') are resolved by cyclonedds
    # with import_module() on the absolute path, not against module globals, so
    # nesting means rewriting them too. Single quotes distinguish them from
    # typename="spatial.core.CovMatrix", which is DDS type identity and must
    # survive untouched.
    ref_re = re.compile(r"'(%s)\." % "|".join(roots))
    for path in sorted(out_dir.rglob("*.py")):
        source = path.read_text()
        patched = import_re.sub(rf"from {package} import \1", source)
        patched = ref_re.sub(rf"'{package}.\1.", patched)
        if patched != source:
            path.write_text(patched)

    (out_dir / "__init__.py").write_text(
        HEADER
        + '"""Generated SpatialDDS 1.8 types. See tools/generate_bindings.py."""\n\n'
        + "".join(f"from . import {r}\n" for r in roots)
        + "\n__all__ = [%s]\n" % ", ".join(f'"{r}"' for r in roots))


def fix_union_discriminators(root: Path, package: str) -> list[str]:
    """Import union discriminators that idlc emitted as bare names."""
    index = _index_definitions(root, package)
    fixed: list[str] = []
    for path in sorted(root.rglob("*.py")):
        source = path.read_text()
        names = set(re.findall(r"discriminator=(\w+)", source))
        missing = [n for n in names if n not in _defined_names(source)]
        if not missing:
            continue
        imports = []
        for name in sorted(missing):
            module = index.get(name)
            if module is None:
                raise SystemExit(
                    f"{path}: union discriminator {name!r} is undefined and no "
                    "generated module defines it, cannot patch, report instead")
            imports.append(f"from {module} import {name}")
            fixed.append(f"{path.relative_to(root)}: {name} <- {module}")
        anchor = "import cyclonedds.idl.types as types\n"
        if anchor not in source:
            raise SystemExit(f"{path}: unexpected generated layout, cannot patch")
        source = source.replace(
            anchor,
            anchor + "\n# generate_types_18.py: idlc emits this discriminator as a bare name\n"
            + "\n".join(imports) + "\n", 1)
        path.write_text(source)
    return fixed


def fix_python_keyword_fields(root: Path) -> dict[str, dict[str, str]]:
    """Rename fields whose IDL name is a Python keyword, preserving wire name.

    The spec legitimately uses ``global`` and ``from`` as field names. idlc >=
    11 emits ``_global`` / ``_from`` itself and we only record the mapping.
    """
    aliases: dict[str, dict[str, str]] = {}
    field_re = re.compile(r"^(    )(\w+)(\s*:\s.*)$")
    class_re = re.compile(r'^class (\w+)\(.*typename="([^"]+)"')

    for path in sorted(root.rglob("*.py")):
        original = path.read_text()
        out: list[str] = []
        typename: str | None = None
        for line in original.splitlines():
            m = class_re.match(line)
            if m:
                typename = m.group(2)
                out.append(line)
                continue
            f = field_re.match(line)
            if f and typename and f.group(2).startswith("_") and keyword.iskeyword(f.group(2)[1:]):
                aliases.setdefault(typename, {})[f.group(2)] = f.group(2)[1:]
                out.append(line)
                continue
            if f and keyword.iskeyword(f.group(2)) and typename:
                name = f.group(2)
                out.append(f"{f.group(1)}{name}_{f.group(3)}")
                out.append(f'{f.group(1)}annotate.member_name("{name}_", "{name}")')
                aliases.setdefault(typename, {})[f"{name}_"] = name
                continue
            out.append(line)
        new_source = "\n".join(out) + "\n"
        if new_source != original:
            path.write_text(new_source)
    return aliases


def write_field_aliases(out_dir: Path, aliases: dict[str, dict[str, str]]) -> None:
    lines = [HEADER,
             '"""Python attribute -> IDL field name, for fields renamed to dodge',
             'Python keywords. See fix_python_keyword_fields in the generator."""',
             "", "FIELD_ALIASES = {"]
    for typename in sorted(aliases):
        lines.append(f'    "{typename}": {{')
        for py, wire in sorted(aliases[typename].items()):
            lines.append(f'        "{py}": "{wire}",')
        lines.append("    },")
    lines += ["}", "", "",
              "def wire_name(typename: str, attr: str) -> str:",
              '    """The IDL field name for a generated attribute."""',
              "    return FIELD_ALIASES.get(typename, {}).get(attr, attr)", ""]
    (out_dir / "_field_aliases.py").write_text("\n".join(lines))


# ---------------------------------------------------------------------------

def generate(spec_idl: Path, out_dir: Path, package: str) -> list[str]:
    if shutil.which("idlc") is None:
        raise SystemExit("idlc not found on PATH")
    with tempfile.TemporaryDirectory() as tmp:
        staging = Path(tmp) / "staging"
        run_idlc(spec_idl, staging)
        if out_dir.exists():
            shutil.rmtree(out_dir)
        # Nest first: the discriminator imports must name the final package.
        nest_packages(staging, out_dir, package)
        fixed = fix_union_discriminators(out_dir, package)
        aliases = fix_python_keyword_fields(out_dir)
        write_field_aliases(out_dir, aliases)
        for tn in sorted(aliases):
            for py, wire in sorted(aliases[tn].items()):
                fixed.append(f"{tn}: {wire} -> {py} (+member_name)")
    return fixed


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--spec", type=Path, default=DEFAULT_SPEC,
                    help="tree containing idl/v1.8 (default: this repository)")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    a = ap.parse_args()

    spec_idl = a.spec / "idl" / "v1.8"
    if not spec_idl.is_dir():
        raise SystemExit(f"not found: {spec_idl}")

    # Which specification revision these bindings came from.
    #
    # Read from <spec>/idl/PROVENANCE when the IDL is vendored, because
    # `git rev-parse` in a vendored tree reports the commit of the repository
    # holding the copy, not the specification it was copied from. That is a
    # silent and misleading wrong answer: the point of recording a pin is
    # being able to trace a binding tree back to the IDL that produced it.
    # Falls back to git for a real SpatialDDS-spec checkout.
    pin = ""
    prov = a.spec / "idl" / "PROVENANCE"
    if prov.is_file():
        for line in prov.read_text().splitlines():
            if line.strip().startswith("commit"):
                pin = line.split("=", 1)[1].strip()
                break
    source = str(prov) if pin else "git"
    if not pin:
        r = subprocess.run(["git", "-C", str(a.spec), "rev-parse", "HEAD"],
                           capture_output=True, text=True)
        pin = r.stdout.strip() if r.returncode == 0 else ""

    print(f"spec {a.spec}")
    print(f"idl  {spec_idl}")
    fixed = generate(spec_idl, a.out, PACKAGE)
    print(f"out  {a.out}")
    for f in fixed:
        print(f"  patched: {f}")
    (a.out / "_provenance.py").write_text(
        HEADER + f'SPEC_COMMIT = "{pin}"\nSPEC_VERSION = "1.8"\n')
    print(f"  provenance: SPEC_COMMIT = {pin}  (from {source})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
